# Generated by Django 2.2.12 on 2020-09-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintaining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('care', models.CharField(choices=[('C', 'Corrective'), ('P', 'Preventative'), ('R', 'Routine')], default='C', max_length=1)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Toy')),
            ],
        ),
    ]
