# Generated by Django 2.2.12 on 2020-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_insect'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='insects',
            field=models.ManyToManyField(to='main_app.Insect'),
        ),
    ]
